name: "Install metal extra dev dependencies - ubuntu-20.04"
description: "Installs tt-metal extra dev dependencies on ubuntu-20.04 GitHub Actions
runners"

inputs:
  os:
    description: 'Runner OS'
    required: true

runs:
  using: "composite"
  steps:
    - name: Verify ubuntu only
      shell: bash
      run: |
        if ! echo ${{ inputs.os }} | grep -q "ubuntu"; then
          echo "${{ inputs.os }} does not seem to be ubuntu"
        fi
    - name: Assert requested os exists in dependencies
      shell: bash
      run: |
        if ! jq -e ".\"${{ inputs.os }}\" != null" $GITHUB_ACTION_PATH/dependencies.json; then
          echo "${{ inputs.os }} does not exist as a supported os in $GITHUB_ACTION_PATH/dependencies.json"
        fi
    - name: Retrieve and install pkg deps based on OS
      id: retrieve-pkg-deps
      shell: bash
      run: |
        DEPENDENCIES=$(jq -r --arg os "${{ inputs.os }}" '.[$os] | .[]' $GITHUB_ACTION_PATH/dependencies.json)
        echo $DEPENDENCIES
        sudo apt update
        sudo apt install -y --no-install-recommends $DEPENDENCIES
    - name: Install doxygen
      shell: bash
      run: |
        curl -L "https://www.doxygen.nl/files/doxygen-1.9.6.linux.bin.tar.gz" -o doxygen-1.9.6.linux.bin.tar.gz
        tar -xvf doxygen-1.9.6.linux.bin.tar.gz
        cd doxygen-1.9.6
        sudo make install
